### ISSUE TITLE
Request for assistance on constructing finite element images from lung CT in EIDORS

### ISSUE THREAD

**Issue by popular1119** [WondooSeo/Making_EIT_Data_with_EIDORS#1]
Dear Dr. Wondoo Seo,
I hope this message finds you well. My name is Peng Piao, and I am currently working on a project involving Electrical Impedance Tomography (EIT). I have been exploring various methods and tools to construct finite element images from lung CT scans using EIDORS. Despite my efforts, I have not been able to achieve the desired results.
I have read numerous papers and visited several websites, but I still face challenges in this area. Given your expertise and contributions to the field, I am reaching out to seek your guidance on the following:
1. Tools and Software: Could you please share which tools and software you used to construct finite element images from lung CT scans in EIDORS? Any recommendations on specific versions or additional plugins would be highly appreciated.
2. Tutorials and Resources: Are there any specific tutorials, guides, or resources that you found particularly helpful when working on similar projects? Any links or references would be extremely beneficial.
3. Step-by-Step Process: If possible, could you provide a brief overview or a step-by-step guide on how you approached this task? Understanding your workflow would help me identify any gaps in my current methodology.
Shape Library: I understand that customizing my own finite elements requires modifying the shape_library.mat in MATLAB, but I am currently unsure how the data within this structure is generated. Could you provide some detailed information or references on how to generate these data?
Your insights and advice would be invaluable to my research. I am eager to learn from your experience and apply your recommendations to overcome the challenges I am facing.
Thank you very much for your time and assistance. I look forward to your response.
Best regards,
Peng Piao
Email: pengpiao1119@gmail.com

**Comment by WondooSeo** [comment]
Dear Peng Piao,

Thank you for visit my project and leave corteous question. I wish this comment helps you.
Before getting started, keep in mind that my answer will be not accurate at all since I discontinued my EIT research since 2022.

1. I used two of FEM programs; COMSOL and MATLAB + EIDORS.
The first one, COMSOL, is powerful tool for solving FEM problems. But the problem was, in my case, COMSOL was way too hard to get used to. Also, you have to pay it for using it legally and costs may a lot.
The second one, EIDORS, is a kind of third party package of MATLAB. You have to download it from EIDORS homepage and move it to installed MATLAB folder, I guess. Furthermore, you have to download Netgen and set the folder path with MATLAB cmd. Also, you have to install some required MATLAB toolbox add-on. But this is the only hard point of EIDORS setting. If you set properly, then you can run my codes by following README. I uploaded FER and GREIT methods, and this will help you to make lung EIT images.
Unfortunately, this project has not been updated over 2 years and thus recommending appropriate of those versions is hard for me now, so please understand it.

2. Well, I learned it from zero actually. The codes I uploaded is like an essence of what I've done with many helps from others. It's a sad thing that there is few EIT researchers, and few tutorials and resources thereafter. The only thing I remember right now is codes from EIDORS official website might help you to get a sence.

3. The flow is simple; Find or get some axial lung images, point out thorax and lung boundary appropriately(If you point way too much, it will be hard to calculate it), save x & y points at shape_library.mat, and load. EIDORS embedded some examples of image points in shape_libirary.mat, and tutorials in EIDORS official website. That'll help when you analyze it carefully. After making boundaries, make electrodes with appropriate codes, then FEM image will be generated. I uploaded 6 normal-look and 3 obese-look thorax & lungs codes and this codes will help you to get further your research, I hope.

I am sorry that answers above may not you wanted, but wish these comments will be helpful as much as I could.

Sincerely yours,
Won-Doo Seo

PS) Thank you for saying me Dr., but my best degree is M. Sc.. Never mind! Ha ha :)

**Comment by popular1119** [comment]
Hello Won-Doo Seo,

First of all, thank you for the information and help you provided earlier. I have been using Eidors for a year in my previous research and have become quite familiar with many tutorials. I greatly appreciate the code you shared on GitHub, which I was able to run perfectly.

Moving forward, I will be conducting some experiments and will keep you updated with any information and questions I may have. I hope you can provide me with some assistance. I apologize in advance if I become a bit bothersome, and I hope you can bear with me, haha.

Thank you once again!

Best regards,

Peng Piao

**Comment by WondooSeo** [comment]
Dear Peng Piao,

It is great to hear that my codes work well in yours! Thanks you!
Feel free to make an issue if you have any troublemsome of your research. I'll help as much as possible.

Thank you!

Sincerely yours,
Won-Doo Seo
